# Generated by Django 5.0.6 on 2024-12-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Kullanici',
        ),
    ]
