# Generated by Django 5.0.6 on 2024-12-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sikayetler', to='core.kullanici')),
            ],
        ),
    ]
