# Generated by Django 5.0.6 on 2024-12-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sikayet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Durak',
            fields=[
                ('Durak_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Durak_Adi', models.CharField(max_length=255, unique=True)),
                ('Kapi_Sayisi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tramvay',
            fields=[
                ('Tramvay_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hat_Ismi', models.CharField(max_length=255)),
                ('Vagon_Sayisi', models.IntegerField()),
                ('Sefer_Baslangic_Saati', models.TimeField()),
                ('Sefer_Bitis_Saati', models.TimeField()),
                ('Sefer_Yonu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kapi',
            fields=[
                ('Kapi_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Isik_Durumu', models.CharField(max_length=255)),
                ('Durak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapilar', to='core.durak')),
            ],
        ),
        migrations.CreateModel(
            name='Kamera',
            fields=[
                ('Kamera_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Durum', models.CharField(max_length=255)),
                ('Giren_Yolcu_Sayisi', models.IntegerField()),
                ('Cikan_Yolcu_Sayisi', models.IntegerField()),
                ('Giren_Engelli_Sayisi', models.IntegerField()),
                ('Cikan_Engelli_Sayisi', models.IntegerField()),
                ('Kapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kameralar', to='core.kapi')),
            ],
        ),
        migrations.CreateModel(
            name='DurakTramvay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beklenen_Giris_Saati', models.TimeField()),
                ('Giris_Saati', models.TimeField()),
                ('Cikis_Saati', models.TimeField()),
                ('Tarih', models.DateField()),
                ('Durak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.durak')),
                ('Tramvay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tramvay')),
            ],
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('Vagon_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Yolcu_Kapasitesi', models.IntegerField()),
                ('Engelli_Kapasitesi', models.IntegerField()),
                ('Yolcu_Sayisi', models.IntegerField()),
                ('Engelli_Sayisi', models.IntegerField()),
                ('Yolcu_Yogunlugu', models.CharField(max_length=255)),
                ('Tramvay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tramvay')),
            ],
        ),
        migrations.CreateModel(
            name='Gecis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toplam_Gecen_Yolcu_Sayisi', models.IntegerField()),
                ('Toplam_Gecen_Engelli_Sayisi', models.IntegerField()),
                ('Saat', models.TimeField()),
                ('Tarih', models.DateField()),
                ('Kapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecisler', to='core.kapi')),
                ('Vagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecisler', to='core.vagon')),
            ],
            options={
                'unique_together': {('Kapi', 'Vagon')},
            },
        ),
    ]
